spring:
  application:
    name: chronicle-backend
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#  datasource:
#    url: jdbc:mysql://localhost:3306/chronicle?useUnicode=yes&characterEncoding=UTF-8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: Jithin123
  data:
    mongodb:
      uri: mongodb+srv://jithinsp001:KX6oSo80nJYGjPK5@mongocluster.0itei1i.mongodb.net/chronicle?retryWrites=true&w=majority&appName=MongoCluster
  datasource:
    url: jdbc:mysql://34.93.111.216:3306/chronicle?useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ~T$+8Hf"1<IU9EGA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

server:
  port: 9000

jwt:
  secret: supersecret

app:
  client:
    url: http://localhost:4200