name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Rename JAR to fixed name
      run: mv target/*.jar target/chronicle.jar

    - name: Copy JAR to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "target/chronicle.jar"
        target: "${{ secrets.APP_DIRECTORY }}"

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          pkill -f 'chronicle' || true

          cd ${{ secrets.APP_DIRECTORY }}

          DATABASE_URL=jdbc:mysql://localhost:3306/chronicle \
          DATABASE_USERNAME=chronicle \
          DATABASE_PASSWORD=password \
          SERVER_PORT=9000 \
          SET_API_LOG_ACTIVE=false \
          nohup java -Xmx128m -Xms64m -jar chronicle.jar > nohup.out 2>&1 &
